server:
  port: 2001
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:2000/eureka/
# git管理配置
spring:
  cloud:
    config:
      server:
        git:
          username: ahaqwjwk@163.com
          password: 3g2,eday726
          uri: https://github.com/ShaunaVayne/spring-config-demo.git
          search-paths: my-config
  application:
    name: allpay-config
