server:
  port: 2001
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:2000/eureka/
# git管理配置
spring:
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared
  profiles:
    active: native
  application:
    name: allpay-config
logging:
  file: ./log/allpay-config.log

